### PR TITLE
add multiple entities support to crud command

### PR DESCRIPTION
**Pull request by RayMMond**
crud command now support generating multiple entities. 
And minor refactoring for command base class.

### CODE REVIEW

**Comment by wakuflair** [comment]
I think there will be too many file changes for users.
And If there's a error during generating, it's hard to figure out what's the reason.

If users do want to generate multiple entities, they can easily write a simple .bat to do that.
So I think this is not necessary.

What' your opinion, @gdlcf88

**Comment by gdlcf88** [comment]
In my experience, generating code for multiple entities is not a frequent need, and it is easy to be implemented by customized script.

**Comment by RayMMond** [comment]
scripts make sense, and I overlooked the problem of error handling, closing this now.

**Comment by papyr** [comment]
Hello I would like to chime in. If I was doing any enterprise app it gets cumber some with more than 20 entities

The core advantage is to script out a previous config file or json file that has all the entities setting when a new release maybe out.

**Pull request closed without merging**
