### PR TITLE
Fix module commands for abp4.4+

### PR DESCRIPTION
**Pull request by JadynWong**
Fix module commands for abp4.4+

https://github.com/EasyAbp/AbpHelper.CLI/pull/152#issuecomment-912335455

### CODE REVIEW

**Comment by wakuflair** [comment]
I run latest abphelper (v0.8.3) module commands on an ABP 5.0.1 project, but didn't found the error,
is this PR still needed?

**Comment by JadynWong** [comment]
> I run latest abphelper (v0.8.3) module commands on an ABP 5.0.1 project, but didn't found the error, is this PR still needed?

I will check again.  Also does the module you're testing contain an EntityFramework project?

**Comment by wakuflair** [comment]
> > I run latest abphelper (v0.8.3) module commands on an ABP 5.0.1 project, but didn't found the error, is this PR still needed?
> 
> I will check again. Also does the module you're testing contain an EntityFramework project?

Nope, maybe that will cause error.
Let's see your check result :)

**Comment by JadynWong** [comment]
1. Run `abp new Acme.BookStore`
2. Run `abphelper module add -soecahlw EasyAbp.PrivateMessaging`
3. Get error result
image

**Comment by gdlcf88** [comment]
I merged it into the [gui-used](https://github.com/EasyAbp/AbpHelper.CLI/tree/gui-used) branch used by [AbpHelper GUI](https://github.com/EasyAbp/AbpHelper.GUI) to apply the changes temporarily.

This PR is still waiting for @wakuflair to review it and merge it into the primary branch if needed.

**Pull request merged**
