### PR TITLE
Add file-scoped namespace support

### PR DESCRIPTION
**Pull request by yellow-dragon-cloud**

### CODE REVIEW

**Comment by gdlcf88** [comment]
Thank you @yellow-dragon-cloud, could you please revert the `Version="5.1.3"` to `Version="$(AbpVersion)"` and then update the ABP package version in Directory.Build.props?

https://github.com/EasyAbp/AbpHelper.CLI/blob/293b2307cdc5dbd4b9da9a10996b75d8ba9a2798/Directory.Build.props#L4

It helps to unitize the ABP version, and we use this property to detect the ABP version of each EasyAbp module (including AbpHelper).

[ABP version](https://abp.io)

**Comment by gdlcf88** [comment]
I merged it into the [gui-used](https://github.com/EasyAbp/AbpHelper.CLI/tree/gui-used) branch used by [AbpHelper GUI](https://github.com/EasyAbp/AbpHelper.GUI) to apply the changes temporarily.

This PR is still waiting for @wakuflair to review it and merge it into the primary branch if needed.

**Comment by JadynWong** [comment]
`BaseParserStep<TType>` should also use the same changes

**Comment by gdlcf88** [comment]
We are moving the templates to file-scoped since the startup template has used it.

https://github.com/EasyAbp/AbpHelper.CLI/pull/177

**Comment by gdlcf88** [comment]
Thanks, @yellow-dragon-cloud @JadynWong.

**Pull request merged**
